### ISSUE TITLE
Does not work in Firefox 72.0.2/Linux64

### ISSUE THREAD

**Issue by abetaev** [lgarron/clipboard-polyfill#126] opened 2020-02-02 19:31 UTC
Hi

I have the following in the `head` section of my HTML page:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard-polyfill/2.8.6/clipboard-polyfill.js"></script>`

But it behaves exactly the same way as without this line when I'm trying to `clipboard.writeText('something')`: throwing undefined as result of promise returned by `writeText`.

p.s.
Occasionally, i also have Chromium with the following version: Version 79.0.3945.130 (Developer Build) built on Debian 10.2, running on Debian 10.2 (64-bit)
And in Chromium clipboard operation works just fine, as specified. No polyfill required to solve anything there. But I noticed that this library makes `clipboard` object available from `window` object. Without it `clipboard` object is accessible only through `navigator.clipboard`. Not sure if it's an issue, but MDN says that `navigator.clipboard` is the standard way to go.

**Comment by lgarron** [comment] 2020-02-04 19:01
I believe you're running up against an intentional design tradeoff: this library is actually a ponyfill rather than a polyfill. https://github.com/sindresorhus/ponyfill

I expect most users to be using modules/build systems, but if you're using the UMD definition directly in the browser, you should call `window.clipboard`. The library will itself call `navigator.clipboard` if it exists.

I'm open a PR clarifying this in the README!

**Comment by laberning** [comment] 2020-07-21 06:56
I have the same problem with Firefox 78 on Windows. When I add clipboard-polyfill.promise.js to the website, then an error `Uncaught TypeError: r.read is undefined` is thrown.

I think it is caused by `var r=navigator.clipboard,o=null==r?void 0:r.read.bind(r)`

On Firefox `navigator.clipboard` exists. But `navigator.clipboard.read` does not exist. So the bind goes into an error.

**Comment by lgarron** [comment] 2020-07-21 08:54
This should be fixed in the latest pre-release already: https://github.com/lgarron/clipboard-polyfill/releases/tag/v3.0.0-pre5

@laberning, could you check if that works for you?

**Comment by lgarron** [comment] 2020-07-21 08:57
Actually, it's had time to bake a while. I think I'll go ahead and release v3.0.0, and I can release a point version if there are still issues.

**Comment by laberning** [comment] 2020-07-21 10:16
@lgarron Thanks for digging into this. Yes, that pre-release Version does indeed fix the issue for us.

**Closed** 2020-07-21 18:31 UTC
