### ISSUE TITLE
Copying HTML on Android Chrome doesn’t work

### ISSUE THREAD

**Issue by robertu7** [lgarron/clipboard-polyfill#168] opened 2024-05-16 23:59 UTC
### Code to reproduce
```
const item = new clipboard.ClipboardItem({
  "text/html": new Blob(
    ["<i>Markup</i> <b>text</b>. Paste me into a rich text editor."],
    { type: "text/html" }
  ),
  "text/plain": new Blob(
    ["Fallback markup text. Paste me into a rich text editor."],
    { type: "text/plain" }
  ),
});
await clipboard.write([item]);
```

It will fallback to copy the plain text instead.

### Device Info
* **Browser**: Chrome 125.0.644.53
* **OS**: Android

**Comment by lgarron** [comment] 2024-05-17 07:25
I can't reproduce this issue in Chrome 124 (Stable) or Chrome 125 (beta) on a Google Pixel 3. Both copy rich text.
Could you provide more details about how you're running into this?

**Comment by lgarron** [comment] 2024-05-23 07:08
Closing for now — please feel free to reopen or file a new issue if you have more details!

**Closed by lgarron** 2024-05-23 07:08 UTC
