### ISSUE TITLE
Clarify usage

### ISSUE THREAD

**Issue by the-spyke** [lgarron/clipboard-polyfill#77] opened 2018-02-19 14:47 UTC
The package is named as a `polyfill`, but it does not actually polyfill global objects. Please update the `Usage` section to something like this:

Get the source using one of the following:

In a browser:
- Download `build/clipboard-polyfill.js` and include it using a `<script>` tag.

In a bundler like `Browserify/Webpack`:
- Run `npm install clipboard-polyfill` command.
- Import the package:
   ```javascript
   // Common JS
   const clipboard = require('clipboard-polyfill');

   // ES Modules
   import clipboard from 'clipboard-polyfill';
   ```

**Comment by lgarron** [comment] 2018-02-20 00:27
I'd prefer to keep it more concise, since it's taking up spaceat the top. How about replacing the current second bullet?

- `npm install clipboard-polyfill` and import as `clipboard`.

**Comment by the-spyke** [comment] 2018-02-20 08:03
Good enough :-)

**Comment by lgarron** [comment] 2018-02-21 01:18
Thanks. :-)

**Comment by Mocha--** [comment] 2018-03-13 03:21
Hi,

Could you please provide a typescript import demo?

I tried to import clipboard from 'clipboard-polyfill' in its version 2.4.6, by which the imported clipboard turned out to be undefined.

**Comment by ochampet** [comment] 2018-06-22 18:28
I am running on the same issue as above.  I cannot use the library in typescrypt. It is always undefined

**Comment by lgarron** [comment] 2018-06-23 20:57
Alright, there are enough requests here that I think you've convinced me we should have something in the README. :-)

@Mocha-- and @ochampet, could you confirm that this works for you?

    import clipboard from "clipboard-polyfill"
    clipboard.writeText("Hello World!");

**Comment by lgarron** [comment] 2018-08-03 20:58
> @lgarron I gave up using this lib. Seems not working on Typescript.

Is this still the case? Could you let me know where you run into an issue?

**Comment by ost12666** [comment] 2018-09-02 17:49
I just tried with TypeScript the code above and it does exception as writeText does not exist. The d.ts file seems to define writeText as static method but it seems to be part of the prototype and not a property on clipboard

**Comment by lgarron** [comment] 2018-09-02 18:54
What code are you using? This works for me:

    npm install clipboard-polyfill
    echo -e 'import clipboard from "clipboard-polyfill"\nclipboard.writeText("Hello World!");' > test.ts
    tsc test.ts

**Comment by Teoxoy** [comment] 2018-10-01 20:30
I had the same problem. I was trying to pass `clipboard.writeText` as a parameter to `.then` and I got an error. Example:
Doesn't work: `somePromiseThatReturnsAString.then(clipboard.writeText)`
Works: `somePromiseThatReturnsAString.then(s => clipboard.writeText(s))`

I had some wired problem like this where I was trying to pass `Math.min` to `Array.reduce()` and it didn't work either.

I'm not sure where the problem lies tho.
Btw I'm using TypeScript too.

**Comment by lgarron** [comment] 2018-10-02 06:50
> Doesn't work: `somePromiseThatReturnsAString.then(clipboard.writeText)`

Ah, there's the issue! This isn't specific to `clipboard-polyfill`, but you have make sure that `clipboard.writeText` receives `clipboard` as its value for `this`:

    // Explicit `bind`:
    somePromiseThatReturnsAString.then(clipboard.writeText.bind(clipboard))

    // Arrow function
    somePromiseThatReturnsAString.then(text => clipboard.writeText(text))

    // `await` (requires being in an async function)
    clipboard.writeText(await somePromiseThatReturnsAString)

This isn't obvious, because many browsers now bind functions like `console.log` for convenience so that you don't have to do this – but it's necessary in the general case. If you try it in Chrome, you'll see that `somePromiseThatReturnsAString.then(navigator.clipboard.writeText)` also fails.

I don't think it's a good idea to add a convenience to the polyfill that doesn't work with the API itself, so you'll have to use one of the approaches above.

**Comment by Teoxoy** [comment] 2018-10-02 07:29
Oh, yeah I see.
I think it's fine how it is since as you said the API doesn't have it either.

**Comment by jamesthurley** [comment] 2018-10-09 15:08
The `import clipboard from 'clipboard-polyfill';` method didn't work for me in TypeScript, however I was able to use the `const clipboard = require('clipboard-polyfill');` version.  A bit untidy, but better than nothing.

**Comment by lgarron** [comment] 2018-10-10 08:33
> The `import` syntax failed for me with the `clipboard` object being undefined at runtime.

Could you provide more details about your environment?
Is it possible that source code transformations like tree shaking remove the `clipboard` object?

**Comment by jamesthurley** [comment] 2018-10-10 09:54
Hi @lgarron, I created a small project to reproduce the issue and in the process found out that the problem disappears from TypeScript 2.7 and beyond (I was on 2.5.3 in the problematic project).

They did tweak the import behaviour with [that release](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop).

If it is of interest, the project to reproduce the issue is here:
https://github.com/jamesthurley/clipboard-polyfill-test

However from my perspective the issue is closed 👍

**Comment by lgarron** [comment] 2018-10-10 22:15
> Hi @lgarron, I created a small project to reproduce the issue and in the process found out that the problem disappears from TypeScript 2.7 and beyond (I was on 2.5.3 in the problematic project).
> 
> They did tweak the import behaviour with [that release](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop).

Thanks for the investigation!

Do you know what works for older versions of TypeScript? `import * as clipboard from "clipboard-polyfill"`?

**Comment by jamesthurley** [comment] 2018-10-11 11:44
I'm not sure.. I tried a few ways at the time including `import * as clipboard from "clipboard-polyfill"` but only had luck with using `require`.

I have read that it's better to [avoid export default](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html), which would sidestep the issue but would obviously be a breaking change for you.

**Comment by sophister** [comment] 2018-10-22 09:22
I'm using Typescript `3.1.3`, `import * as clipboard from "clipboard-polyfill"` **work** and, `import clipboard from "clipboard-polyfill"` **NOT** work

**Comment by lgarron** [comment] 2018-10-22 18:40
Folks having issues: could you try `v2.6.0` and see if that helps?

**Comment by lgarron** [comment] 2018-10-22 18:43
> `polyfill"` works?

Never mind, that broke the direct browser script include. I'll take a closer look when I have time to actually dig into the code. (For `v2.6.0` I just published a draft fix I had lying around.)

**Comment by lgarron** [comment] 2018-10-24 05:34
I spent some time [testing compatibility](https://github.com/lgarron/clipboard-polyfill/tree/master/test/import) of various import formats, and I can only summarize the state of incompatibility in the ecosystem as "insane".

It seems that the most compatible (but not fully compatible!) option is to export the polyfill at the `module.exports` level rather than `module.exports.default`.

Folks in this thread who were having issues before: could you upgrade to `v3.0.0-beta` and test whether that `import * as clipboard from "clipboard-polyfill"` works?

**Comment by jamesthurley** [comment] 2018-10-24 17:43
The beta looks good to me.  Below is an update of what I've found:

**clipboard-polyfill 2.x**
*Test Project*
✔️ In my [test project](https://github.com/jamesthurley/clipboard-polyfill-test), which used the Parcel bundler for simplicity, the `import clipboard from 'clipboard-polyfill'` syntax worked for TypeScript 2.7 and above.

*Actual Project*
❌ In my actual project, which uses Webpack, I found that `import clipboard from 'clipboard-polyfill'` still failed even on TypeScript > 2.7.

**clipboard-polyfill 3.0.0-beta**
*Test Project*
✔️ The `import * as clipboard from "clipboard-polyfill"` syntax works (even on Typescript 2.6.2). The `require('clipboard-polyfill')` syntax also still works.

*Actual Project*
✔️ The `import * as clipboard from "clipboard-polyfill"` is working in this project as well.

------

Btw, it might be intentional but I had to reference the beta directly from GitHub in my package.json (`"clipboard-polyfill": "github:lgarron/clipboard-polyfill#v3.0.0-beta"`) as it isn't in NPM.

**Comment by lgarron** [comment] 2018-10-25 06:16
> Btw, it might be intentional but I had to reference the beta directly from GitHub in my package.json (`"clipboard-polyfill": "github:lgarron/clipboard-polyfill#v3.0.0-beta"`) as it isn't in NPM.

I hit some publishing issues, which at this point has resulted in the version being unpublished. `clipboard-polyfill@3.0.0-beta2` should work, if anyone else could try this.

**Comment by Livven** [comment] 2019-11-25 14:24
Could it be that setting `esModuleInterop` to `true` in the `tsconfig.json` fixes all these issues? At least using recent TypeScript versions I have had no issues this way.

**Comment by lgarron** [comment] 2020-07-27 05:48
Closing this for now, since the library has changed (including an actual polyfill option). If anyone still has issues, please file a new issue!

**Closed** 2020-07-27 05:51 UTC
