### ISSUE TITLE
iOS Safari copying empty string

### ISSUE THREAD

**Issue by TheAlmightyBob** [lgarron/clipboard-polyfill#111] opened 2019-06-17 23:36 UTC
This is a follow-up to https://github.com/lgarron/clipboard-polyfill/issues/42#issuecomment-497145354

When we pass a text string to `writeText`, it works on every platform/browser except iOS, where it instead copies an empty string (it doesn't just fail to copy, it actually writes an empty string to the clipboard).

I don't have a simple repro to give you, but I debugged this together with a couple of Apple's WebKit engineers at WWDC and wanted to share observations.

The issue occurs in the "Fallback 1 for desktop Safari" branch, where it calls `copyUsingTempSelection`. At that point it "successfully" copies the empty string, so the code never reaches the branch labeled "Fallback for iOS Safari." If we removed the `copyUsingTempSelection` branch so that it _does_ reach "Fallback for iOS Safari," _that does work_.

I will note that the WebKit devs were pretty confused by `copyUsingTempSelection`, both by what it's trying to do and why it's considered necessary for desktop Safari.

**Comment by lgarron** [comment] 2019-06-18 00:38
Thanks for taking the time to investigate this!

Safari compat is quite annoying to repro, since Safari releases are tied to OS releases.

> I will note that the WebKit devs were pretty confused by `copyUsingTempSelection`, both by what it's trying to do and why it's considered necessary for desktop Safari.

`copyUsingTempSelection()` exists because `document.execCommand("copy")` fails on Safari if these is no selection: https://bugs.webkit.org/show_bug.cgi?id=156529

Our code tries `copyUsingTempSelection()` before `copyUsingTempElem()` because adding an element to the DOM has side effects (e.g. triggering mutation observers), and I would like to avoid unnecessary side effects as much as possible.

Unfortunately, it seems that iOS and desktop diverge on the bug you're describing: https://bugs.webkit.org/show_bug.cgi?id=177715

If you're still in contact with the WebKit devs, I'd appreciate comments on the two bugs I've linked in order to convey the impression that this is preventing things from working in Safari. :-)

> If we removed the `copyUsingTempSelection` branch so that it _does_ reach "Fallback for iOS Safari," _that does work_.

Does this not reach the "Fallback 2 for desktop Safari." branch?

Overall, I think it's worth making sure that we copy successfully at least on current (and upcoming) versions of all browsers. I'll take a closer look at this.

**Comment by lgarron** [comment] 2019-06-18 00:46
I tried the following on Safari 12.1.1 / iOS 12.3:

- Visit https://garron.net/code/clipboard-polyfill/
- Click on "Copy text (plain)"
- Put the cursor in the paste area and paste.

I observe the correct behaviour: "This text is plain." shows up in the paste area.

The console shows:

    [Info] listener called (clipboard-polyfill, line 13)
    [Info] copyUsingTempElem worked (clipboard-polyfill, line 13)

Do you have a specific configuration that reproduces the issue?

**Comment by TheAlmightyBob** [comment] 2019-06-19 16:51
> If you're still in contact with the WebKit devs

Unfortunately I'm not, and I hadn't seen these issues you linked prior to the meeting. Which is too bad because they did seem pretty keen to make sure there were no bugs on their end. They did make note of this library though, so _maybe_ they'll see this, but no guarantees...

> > If we removed the copyUsingTempSelection branch so that it does reach "Fallback for iOS Safari," that does work.

> Does this not reach the "Fallback 2 for desktop Safari." branch?

I'm _pretty sure_ it did but that `copyUsingTempElem` returned false so it kept going.... it's _theoretically_ possible that we also removed that branch and I'm misremembering, but I don't think so...

> Do you have a specific configuration that reproduces the issue?

Unfortunately at this time I'm not clear on what exactly is involved to repro the issue... I considered holding off on this report because of that but thought it was still worth sharing with you what we'd learned thus far...

**Comment by lgarron** [comment] 2023-01-05 09:15
iOS 16 Safari seems to be fairly well behaved on my iPhone.

Since old Safari versions are fairly rare in the wild, I'm going to close this issue for now.

**Closed by lgarron** 2023-01-05 09:15 UTC
Labels: external issue?
